use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FieldId {
    Fore3,
    Fore2,
    Fore1,
    Village2,
    Ruin4,
    Ruin3,
    Ruin2,
    Ruin1,
    De1,
    Village1,
    De2,
    De3,
    De4,
    Dun1,
    Dun2,
    Dun3,
    Office,
    ForeverFall04,
    ForeverFall03,
    ForeverFall02,
    ForeverFall01,
    Pilai,
    Dun4,
    Dun5,
    TCave,
    MCave,
    DCave,
    Iron1,
    Iron2,
    IceUra,
    Sod1,
    Ice1,
    QuestIv,
    Castle,
    Greedy,
    Ice2,
    Boss,
    Lost,
    LostTemple,
    FallGame,
    Dun7,
    Dun8,
    Dun6,
    Dun9,
    Mine1,
    Slab,
    AncientW,
    CondadoPecador,
    Dc1,
    Ba1,
    HeartOfFire,
    Temple2,
    AwFl,
    CrystalNest,
    LandOfNurwn,
    Arena,
    Coliseu,
    HappyPt,
    HappyPt1,
}

impl FieldId {
    pub fn from_raw(value: i32) -> Option<Self> {
        Some(match value {
            0 => Self::Fore3,
            1 => Self::Fore2,
            2 => Self::Fore1,
            3 => Self::Village2,
            4 => Self::Ruin4,
            5 => Self::Ruin3,
            6 => Self::Ruin2,
            7 => Self::Ruin1,
            8 => Self::De1,
            9 => Self::Village1,
            10 => Self::De2,
            11 => Self::De3,
            12 => Self::De4,
            13 => Self::Dun1,
            14 => Self::Dun2,
            15 => Self::Dun3,
            16 => Self::Office,
            17 => Self::ForeverFall04,
            18 => Self::ForeverFall03,
            19 => Self::ForeverFall02,
            20 => Self::ForeverFall01,
            21 => Self::Pilai,
            22 => Self::Dun4,
            23 => Self::Dun5,
            24 => Self::TCave,
            25 => Self::MCave,
            26 => Self::DCave,
            27 => Self::Iron1,
            28 => Self::Iron2,
            29 => Self::IceUra,
            30 => Self::Sod1,
            31 => Self::Ice1,
            32 => Self::QuestIv,
            33 => Self::Castle,
            34 => Self::Greedy,
            35 => Self::Ice2,
            36 => Self::Boss,
            37 => Self::Lost,
            38 => Self::LostTemple,
            39 => Self::FallGame,
            40 => Self::Dun7,
            41 => Self::Dun8,
            42 => Self::Dun6,
            43 => Self::Dun9,
            44 => Self::Mine1,
            45 => Self::Slab,
            46 => Self::AncientW,
            47 => Self::CondadoPecador,
            48 => Self::Dc1,
            49 => Self::Ba1,
            50 => Self::HeartOfFire,
            51 => Self::Temple2,
            52 => Self::AwFl,
            53 => Self::CrystalNest,
            54 => Self::LandOfNurwn,
            55 => Self::Arena,
            56 => Self::Coliseu,
            57 => Self::HappyPt,
            58 => Self::HappyPt1,
            _ => return None,
        })
    }

    pub fn raw(self) -> i32 {
        match self {
            Self::Fore3 => 0,
            Self::Fore2 => 1,
            Self::Fore1 => 2,
            Self::Village2 => 3,
            Self::Ruin4 => 4,
            Self::Ruin3 => 5,
            Self::Ruin2 => 6,
            Self::Ruin1 => 7,
            Self::De1 => 8,
            Self::Village1 => 9,
            Self::De2 => 10,
            Self::De3 => 11,
            Self::De4 => 12,
            Self::Dun1 => 13,
            Self::Dun2 => 14,
            Self::Dun3 => 15,
            Self::Office => 16,
            Self::ForeverFall04 => 17,
            Self::ForeverFall03 => 18,
            Self::ForeverFall02 => 19,
            Self::ForeverFall01 => 20,
            Self::Pilai => 21,
            Self::Dun4 => 22,
            Self::Dun5 => 23,
            Self::TCave => 24,
            Self::MCave => 25,
            Self::DCave => 26,
            Self::Iron1 => 27,
            Self::Iron2 => 28,
            Self::IceUra => 29,
            Self::Sod1 => 30,
            Self::Ice1 => 31,
            Self::QuestIv => 32,
            Self::Castle => 33,
            Self::Greedy => 34,
            Self::Ice2 => 35,
            Self::Boss => 36,
            Self::Lost => 37,
            Self::LostTemple => 38,
            Self::FallGame => 39,
            Self::Dun7 => 40,
            Self::Dun8 => 41,
            Self::Dun6 => 42,
            Self::Dun9 => 43,
            Self::Mine1 => 44,
            Self::Slab => 45,
            Self::AncientW => 46,
            Self::CondadoPecador => 47,
            Self::Dc1 => 48,
            Self::Ba1 => 49,
            Self::HeartOfFire => 50,
            Self::Temple2 => 51,
            Self::AwFl => 52,
            Self::CrystalNest => 53,
            Self::LandOfNurwn => 54,
            Self::Arena => 55,
            Self::Coliseu => 56,
            Self::HappyPt => 57,
            Self::HappyPt1 => 58,
        }
    }

    pub fn all() -> &'static [Self] {
        const ALL: &[FieldId] = &[
            FieldId::Fore3,
            FieldId::Fore2,
            FieldId::Fore1,
            FieldId::Village2,
            FieldId::Ruin4,
            FieldId::Ruin3,
            FieldId::Ruin2,
            FieldId::Ruin1,
            FieldId::De1,
            FieldId::Village1,
            FieldId::De2,
            FieldId::De3,
            FieldId::De4,
            FieldId::Dun1,
            FieldId::Dun2,
            FieldId::Dun3,
            FieldId::Office,
            FieldId::ForeverFall04,
            FieldId::ForeverFall03,
            FieldId::ForeverFall02,
            FieldId::ForeverFall01,
            FieldId::Pilai,
            FieldId::Dun4,
            FieldId::Dun5,
            FieldId::TCave,
            FieldId::MCave,
            FieldId::DCave,
            FieldId::Iron1,
            FieldId::Iron2,
            FieldId::IceUra,
            FieldId::Sod1,
            FieldId::Ice1,
            FieldId::QuestIv,
            FieldId::Castle,
            FieldId::Greedy,
            FieldId::Ice2,
            FieldId::Boss,
            FieldId::Lost,
            FieldId::LostTemple,
            FieldId::FallGame,
            FieldId::Dun7,
            FieldId::Dun8,
            FieldId::Dun6,
            FieldId::Dun9,
            FieldId::Mine1,
            FieldId::Slab,
            FieldId::AncientW,
            FieldId::CondadoPecador,
            FieldId::Dc1,
            FieldId::Ba1,
            FieldId::HeartOfFire,
            FieldId::Temple2,
            FieldId::AwFl,
            FieldId::CrystalNest,
            FieldId::LandOfNurwn,
            FieldId::Arena,
            FieldId::Coliseu,
            FieldId::HappyPt,
            FieldId::HappyPt1,
        ];
        ALL
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldStateKind {
    QuestZone,
    Village,
    Forest,
    Desert,
    Ruin,
    Dungeon,
    Iron,
    Room,
    Ice,
    Castle,
    Action,
    All,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct FieldPolicy {
    pub can_use_skill: bool,
    pub is_safe_zone: bool,
    pub pvp_allowed: bool,
    pub can_trade: bool,
    pub can_drop: bool,
    pub can_open_shop: bool,
}

impl FieldPolicy {
    pub fn allows_skill_restrictive(&self) -> bool {
        self.can_use_skill
    }
}
