use crate::domain::{
    item::dto::{ItemInfo, PlayerJobMask},
    user_player::dto::{PlayerJob, UserChar},
};

const TRANS_BUFF_SIZE: usize = 4096;
const SR_PLAYBUFF_MAX: usize = 4;
const THROW_ITEM_INFO_MAX: usize = 64;
const INVEN_ITEM_INFO_MAX: usize = 300;
const WAREHOUSE_ITEM_INFO_MAX: usize = 120;
const MYSHOP_LIST_MAX: usize = 32;
const PARTY_PLAYER_MAX: usize = 6;
const SKILL_POINT_COLUM_MAX: usize = 20;

#[derive(Debug, Clone, Copy, Default)]
pub struct ThrowItemInfo {
    pub code: u32,
    pub key: u32,
    pub sum: u32,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct RsPlayPos {
    pub area: u32,
    pub x: i32,
    pub y: i32,
    pub z: i32,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct MyShopSellInfo {
    pub code: u32,
    pub head: u32,
    pub checksum: u32,
    pub price: i32,
    pub kind_currency: i32,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct CastleMaster {
    pub flag: i32,
    pub check_time: u32,
    pub select_skill: i32,
}

#[derive(Debug, Clone)]
pub struct PacketUnitStatusContainer {
    pub length: u16,
    pub header: u32,
    pub amount: i32,
    pub counter: i32,
    pub buffer: [u8; 0x2038],
}

impl Default for PacketUnitStatusContainer {
    fn default() -> Self {
        Self {
            length: 0,
            header: 0,
            amount: 0,
            counter: 0,
            buffer: [0; 0x2038],
        }
    }
}

#[derive(Debug, Clone)]
pub struct PacketSkillStatusContainer {
    pub length: u16,
    pub header: u32,
    pub amount: i32,
    pub buffer: [u8; 0x1FF4],
}

impl Default for PacketSkillStatusContainer {
    fn default() -> Self {
        Self {
            length: 0,
            header: 0,
            amount: 0,
            buffer: [0; 0x1FF4],
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct DefItemInfo {
    pub item: ItemInfo,
    pub durability: [i16; 2],
    pub resistance: [[i16; 2]; 8],
    pub damage: [i16; 4],
    pub attack_rating: [i16; 2],
    pub defense: [i16; 2],
    pub block_rating: [f32; 2],
    pub absorb: [f32; 2],
    pub speed: [f32; 2],
    pub increase_life: [i32; 2],
    pub increase_mana: [i32; 2],
    pub increase_stamina: [i32; 2],
    pub mana_regen: [f32; 2],
    pub life_regen: [f32; 2],
    pub stamina_regen: [f32; 2],
    pub special_defense: [i16; 2],
    pub special_absorb: [f32; 2],
    pub special_speed: [f32; 2],
    pub special_magic_mastery: [f32; 2],
    pub special_mana_regen: [f32; 2],
    pub level_attack_rating: [i32; 2],
    pub job_bit_code_random: Vec<PlayerJobMask>,
    pub item_sec_code_count: usize,
    pub generation_day: [i16; 2],
}

pub struct PartyPlayInfo {
    pub object_serial: u32,
    pub level: u32,
    pub job: PlayerJob,
    pub life: [i32; 2],
    pub x: i32,
    pub z: i32,
}

pub struct TransPartyPlayInfo {
    pub object_serial: u32,
    pub temp: u32,
    pub party_user_count: i32,
    pub play_info: [PartyPlayInfo; PARTY_PLAYER_MAX],
}

#[derive(Debug, Clone, Default)]
pub struct RsPlayInfo {
    // Identity and session
    pub server_id: String,
    pub id: String,
    pub name: String,
    pub code_id: u32,
    pub code_name: u32,
    pub admin_oper_mode: i32,
    pub data_error: u32,
    pub trans_info_flag: i32,
    pub chat_buff_count: i32,
    pub system_line: i32,
    pub char_loading_count: i32,
    pub position: RsPlayPos,
    pub area_play_info_ids: Vec<u32>,
    pub send_list_count: i32,
    pub dec_packet_code: u32,
    pub packet_xor: [u8; 2],
    pub dec_packet_time: u32,
    pub dec_packet_time2: u32,
    pub char_info: UserChar,
    pub char_level_max: i32,
    pub notice_count: u32,
    pub play_buffs: Vec<Vec<u8>>,
    pub play_buff_sizes: Vec<i32>,
    pub play_buff_sleep: i32,

    // Inventory/economy
    pub throw_item_info: Vec<ThrowItemInfo>,
    pub inven_item_info: Vec<ThrowItemInfo>,
    pub warehouse_item_info: Vec<ThrowItemInfo>,
    pub open_warehouse_info_flag: i32,
    pub warehouse_page: i32,
    pub trade_potion_info: [u32; 16],
    pub trade_potion_info_count: i32,
    pub my_shop_list: [MyShopSellInfo; MYSHOP_LIST_MAX],
    pub my_shop_list_count: i32,
    pub my_shop_trade_time: u32,
    pub throw_item_count: i32,
    pub unsaved_money: i32,
    pub server_money: i32,
    pub warehouse_money: i32,

    // Communication/runtime
    pub recv_time_play_buff: u32,
    pub send_play_buff_count: u32,
    pub recv_play_buff_count: u32,
    pub object_serial: u32,
    pub chat_msg_mode: i32,
    pub chat_message: String,
    pub trade_message: String,
    pub trade_msg_code: u32,
    pub sm_sock_handle: Option<usize>,
    pub last_recv_time: u32,
    pub last_motion_recv_time: u32,
    pub update_info_wait_counter: i32,
    pub update_info_warning_counter: i32,
    pub record_base_handle: Option<usize>,
    pub post_box_item_handle: Option<usize>,
    pub post_pass_fail_count: i32,
    pub admin_mode: i32,
    pub hide_mode: i32,
    pub admin_ip: i32,
    pub connect_time: u32,
    pub last_trans_play_user_count: i32,
    pub last_trans_auto_play_count: i32,
    pub connect_count: u32,
    pub frame: i32,
    pub send_play_group_count: u32,
    pub mon_tran_count: u32,
    pub char_trans_count: u32,

    // Combat tracking
    pub hit_monster_count: i32,
    pub chr_target_id: Option<u32>,
    pub target_object_serial: u32,
    pub user_packet_loop: i32,
    pub prev_user_packet_loop: i32,
    pub attack_count: i32,
    pub attack_time: u32,
    pub last_attack_time: u32,
    pub damage_packet_count: i32,
    pub damage_packet_time: u32,
    pub monster_kill_counter: i32,
    pub last_trade_checksum: u32,
    pub last_trade_time: u32,
    pub low_level_present_item: [i16; 2],
    pub start_user_present_item_time: u32,
    pub start_user_present_item_count: u32,
    pub kill_count: i32,
    pub kill_time: u32,
    pub send_attack_count: i32,
    pub send_attack_damage: i32,
    pub recv_attack_count: i32,
    pub recv_attack_damage: i32,
    pub macro_time: u32,
    pub macro_pos_x: i32,
    pub macro_pos_z: i32,
    pub macro_ang_y: i32,
    pub macro_ang_time: u32,
    pub macro_check_time: u32,
    pub send_frames: Vec<u32>,
    pub crack_warning: i32,
    pub time_disconnect: u32,
    pub bad_player: i32,
    pub packet_attack_count: u32,
    pub packet_attack_time: u32,
    pub warning_count: i32,
    pub record_data_buffer_handle: Option<usize>,
    pub record_data_time: u32,

    // Event/accounting
    pub event_mode: i32,
    pub event_score: i32,
    pub event_count: i32,
    pub event_time: u32,
    pub event_param: [i16; 2],
    pub area_out_count: i32,
    pub block_time: i32,
    pub whisper_mode: i32,
    pub event_star_ticket_level: i32,
    pub exp_start: i64,
    pub money_start: i32,
    pub level_start: i32,
    pub exp_in_out_total: i32,
    pub money_in_total: i32,
    pub money_in_out_total: i32,
    pub exp_out: i64,
    pub money_in: i32,
    pub money_out: i32,
    pub last_exp_money_check_time: u32,
    pub last_exp_money_trans_server: u32,
    pub hope_disconnect_time: u32,
    pub client_version: i32,
    pub last_save_time: u32,
    pub game_server_exp: [u32; 8],
    pub n_sprite_time: u32,
    pub client_func_check_1: u32,
    pub client_func_check_2: u32,
    pub func_check_fail_count_1: i32,
    pub func_check_fail_count_2: i32,
    pub func_check_success_count_1: i32,
    pub func_check_success_count_2: i32,
    pub func_check_error_flag: u32,
    pub client_fun_check_1_count: i32,
    pub client_fun_check_2_count: i32,
    pub client_fun_check_next_time: u32,
    pub record_warning_count: i32,
    pub record_warning_exp: i32,
    pub client_os: u32,
    pub client_os_version: [u16; 2],
    pub client_module_checksum: u32,
    pub client_module_count: i32,
    pub damage_packet_key: [u32; 2],
    pub damage_packet_key2: [u32; 2],

    // Party/clan
    pub party_update_flag: u32,
    pub party_info: u32,
    pub party_master_id: Option<u32>,
    pub party_master_object_code: u32,
    pub party_player_ids: Vec<u32>,
    pub party_object_code: [u32; PARTY_PLAYER_MAX],
    pub party_level_average: u32,
    pub party_user_count: i32,
    pub clan_code: u32,
    pub clan_ticket_code: i32,
    pub success_check_clan_code: i32,
    pub guid: String,
    pub password: String,
    pub gp_code_text: String,
    pub disuse_day: i64,
    pub use_period: i32,
    pub gp_code: i32,
    pub gp_type: i32,
    pub period_time: u32,
    pub bl_r_no: i32,
    pub bl_meter: i32,
    pub period_time2: u32,
    pub snd_item_sec_code_count: i32,
    pub recv_item_sec_code_buff: [[i32; 16]; 8],
    pub limit_damage: [i16; 2],
    pub limit_critical: [i16; 2],
    pub server_potion: [[i32; 4]; 3],
    pub relics_active: [bool; 12],
    pub plus_attack_rating: u32,

    // Skill/buff state
    pub skill_last_code: u32,
    pub skill_last_point: u32,
    pub skill_automation_time: u32,
    pub skill_automation_param: i32,
    pub skill_maximize_time: u32,
    pub skill_maximize_param: i32,
    pub skill_physical_absorb_time: u32,
    pub skill_physical_absorb_param: i32,
    pub skill_extreme_shield_time: u32,
    pub skill_extreme_shield_param: i32,
    pub skill_holy_body_time: u32,
    pub skill_holy_body_param: i32,
    pub skill_holy_valor_time: u32,
    pub skill_holy_valor_param: i32,
    pub advent_migal_time: u32,
    pub advent_migal_param: i32,
    pub advent_midranda_time: u32,
    pub advent_midranda_param: i32,
    pub skill_holy_reflection_time: u32,
    pub skill_holy_reflection_param: i32,
    pub skill_enchant_weapon_time: u32,
    pub skill_enchant_weapon_param: i32,
    pub skill_metal_armor_time: u32,
    pub skill_metal_armor_param: i32,
    pub skill_spark_shield_time: u32,
    pub skill_spark_shield_param: i32,
    pub skill_falcon_time: u32,
    pub skill_falcon_damage: [i16; 2],
    pub skill_divine_inhalation_time: u32,
    pub skill_divine_inhalation_param: u32,
    pub skill_triumph_of_valhalla_time: u32,
    pub skill_triumph_of_valhalla_param: u32,
    pub skill_virtual_life_time: u32,
    pub skill_virtual_life_param: u32,
    pub skill_energy_shield_time: u32,
    pub skill_energy_shield_param: u32,
    pub skill_spirit_elemental_time: u32,
    pub skill_spirit_elemental_param: u32,
    pub skill_dancing_sword_time: u32,
    pub skill_dancing_sword_param: u32,
    pub skill_dancing_sword_delay_time: u32,
    pub skill_vanish_time: u32,
    pub skill_vanish_param: u32,
    pub skill_compulsion_time: u32,
    pub skill_compulsion_param: u32,
    pub skill_magnetic_sphere_time: u32,
    pub skill_magnetic_sphere_param: u32,
    pub skill_berserker_time: u32,
    pub skill_berserker_param: u32,
    pub skill_b_berserker_time: u32,
    pub skill_b_berserker_param: u32,
    pub skill_krishna_time: u32,
    pub skill_krishna_param: u32,
    pub skill_assassin_eye_time: u32,
    pub skill_assassin_eye_param: u32,
    pub skill_tenus_time: u32,
    pub skill_tenus_param: u32,
    pub skill_p_enhence_time: u32,
    pub skill_p_enhence_param: u32,
    pub skill_vague_time: u32,
    pub skill_vague_param: u32,
    pub skill_force_of_nature_time: u32,
    pub skill_force_of_nature_param: [u16; 2],
    pub skill_godly_shield_time: u32,
    pub skill_godly_shield_param: u32,
    pub skill_gods_bless_time: u32,
    pub skill_gods_bless_param: u32,
    pub skill_hall_of_valhalla_time: u32,
    pub skill_hall_of_valhalla_param: [u16; 2],
    pub skill_frost_javelin_time: u32,
    pub skill_frost_javelin_param: u32,
    pub skill_regeneration_field_time: u32,
    pub skill_summon_muspell_time: u32,
    pub skill_summon_muspell_param: u32,
    pub skill_chasing_hunt_time: u32,
    pub skill_chasing_hunt_param: u32,
    pub skill_rain_maker_time: u32,
    pub skill_rain_maker_param: u32,
    pub skill_blind_time: u32,
    pub skill_blind_param: u32,
    pub skill_alas_time: u32,
    pub skill_alas_param: u32,
    pub skill_holy_benedic_time: u32,
    pub skill_holy_benedic_param: u32,
    pub skill_amplified_time: u32,
    pub skill_amplified_param: u32,
    pub skill_anima_time: u32,
    pub skill_anima_param: u32,
    pub skill_power_enhence_time: u32,
    pub skill_power_enhence_param: u32,
    pub skill_i_bulkup_time: u32,
    pub skill_i_bulkup_param: u32,
    pub skill_summon_ramiel_time: u32,
    pub skill_summon_ramiel_param: u32,
    pub curse_attack_time: u32,
    pub curse_attack_param: u32,
    pub curse_defence_time: u32,
    pub curse_defence_param: u32,
    pub skill_point: [u8; SKILL_POINT_COLUM_MAX],

    // Prime/booster and timers
    pub force_orb_code: u32,
    pub force_orb_time: u32,
    pub force_orb_damage: u32,
    pub force_orb_save_code: u32,
    pub force_orb_save_time: u32,
    pub force_orb_save_damage: u32,
    pub force_orb_next_set_time: u32,
    pub life_booster_code: u32,
    pub life_booster_time: u32,
    pub life_booster_data: u32,
    pub life_booster_save_code: u32,
    pub life_booster_save_time: u32,
    pub life_booster_save_data: u32,
    pub life_booster_next_set_time: u32,
    pub mana_booster_code: u32,
    pub mana_booster_time: u32,
    pub mana_booster_data: u32,
    pub mana_booster_save_code: u32,
    pub mana_booster_save_time: u32,
    pub mana_booster_save_data: u32,
    pub mana_booster_next_set_time: u32,
    pub stamina_booster_code: u32,
    pub stamina_booster_time: u32,
    pub stamina_booster_data: u32,
    pub stamina_booster_save_code: u32,
    pub stamina_booster_save_time: u32,
    pub stamina_booster_save_data: u32,
    pub stamina_booster_next_set_time: u32,
    pub prime_item_next_set_time: u32,
    pub time_prime_item_x2: u32,
    pub time_prime_item_exp_up: u32,
    pub prime_item_package_code: u32,
    pub time_prime_item_vamp_cuspid: u32,
    pub time_prime_item_mana_recharg: u32,
    pub time_prime_item_mightof_awell: u32,
    pub time_prime_item_mightof_awell2: u32,
    pub time_prime_item_mana_reduce: u32,
    pub time_prime_item_phenix_pet: u32,
    pub time_prime_item_help_pet: u32,
    pub param_prime_item_help_pet: i32,
    pub time_prime_item_vamp_cuspid_ex: u32,
    pub time_prime_item_stamina_reduce: u32,
    pub time_prime_item_big_head: u32,
    pub param_prime_item_big_head: u32,
    pub time_prime_item_vip: u32,
    pub param_prime_item_vip: u32,
    pub pcbang_pet_attack_time: u32,
    pub pcbang_pet_next_set_time: u32,
    pub help_pet_attack_time: u32,
    pub help_pet_next_set_time: u32,
    pub skill_delay_code: u32,
    pub skill_delay_time: u32,
    pub skill_delay_data: u32,
    pub skill_delay_save_code: u32,
    pub skill_delay_save_time: u32,
    pub skill_delay_save_data: u32,
    pub skill_delay_next_set_time: u32,
    pub chat_global_time: u32,

    // Class/quest/battle
    pub link_char_id: Option<u32>,
    pub link_char_code: u32,
    pub bless_castle_damage: [i16; 2],
    pub battle_point: i32,
    pub death_point: i32,
    pub last_kill: String,
    pub top_level: i32,
    pub pvp_time: u32,
    pub pvp_param: i32,
    pub on_battle: i32,
    pub on_hell_gates: i32,
    pub battle_score: i32,
    pub battle_level: i32,
    pub battle_exp: i32,
    pub streak: i32,
    pub weapon_class: i32,
    pub armor_class: i32,
    pub shield_class: i32,
    pub bracelets_class: i32,
    pub gauntlets_class: i32,
    pub boots_class: i32,
    pub ring_class: i32,
    pub amy_class: i32,
    pub shel_class: i32,
    pub time_class: u32,
    pub warehouse_page_time: u32,
    pub quest_start_state: u32,
    pub quest_start_param1: u32,
    pub quest_start_param2: u32,
    pub quest_lv150a_state: u32,
    pub quest_lv150a_param: u32,
    pub quest_lv150a_time: u32,
    pub quest_lv155a_state: u32,
    pub quest_lv155a_param: u32,
    pub quest_lv155a_time: u32,
    pub quest_lv150b_state: u32,
    pub quest_lv150b_param: u32,
    pub quest_lv150b_time: u32,
    pub random_monster_param: u32,
    pub random_monster_time: u32,
    pub checksum: u32,
    pub check_master_clan_time: u32,
    pub castle_master: CastleMaster,
    pub bless_skill_code: u32,
    pub bless_skill_time: u32,
    pub bless_skill_param: u32,
    pub siege_item_scroll_time: u32,
    pub siege_item_scroll_code: u32,
    pub siege_item_scroll_param: u32,
    pub siege_item_stone1_time: u32,
    pub siege_item_stone1_code: u32,
    pub siege_item_stone1_param: u32,
    pub siege_item_stone2_time: u32,
    pub siege_item_stone2_code: u32,
    pub siege_item_stone2_param: u32,
    pub check_play_field_count: [i16; 2],
    pub ha_quest_item_count: u32,
    pub user_exp_time_id: String,
    pub user_exp_time_name: String,
    pub exp_game_time: u32,
    pub exp_game_time_check: u32,
    pub count_min: u32,

    // Sell lists and status containers
    pub sell_attack_items: [u8; 32],  //DefItemInfo.item.code
    pub sell_defense_items: [u8; 32], //DefItemInfo.item.code
    pub sell_etc_items: [u8; 32],     //DefItemInfo.item.code
    pub b32: i32,
    pub b64: i32,
    pub priority_counter: u32,
    pub priority: u32,
    pub afk: u32,
    pub unit_status_counter: i32,
    pub buffer_position: u32,
    pub unit_status_container: PacketUnitStatusContainer,
    pub buffer_position_m: u32,
    pub unit_status_container_m: PacketUnitStatusContainer,
    pub buffer_position_s: u32,
    pub skill_status_container: PacketSkillStatusContainer,
    pub new_unit_status: u32,
    pub last_unit_status: u32,
    pub update_counter1: Vec<u32>,
    pub update_counter2: Vec<u32>,
    pub update_counter3: Vec<u16>,
    pub update_counter4: Vec<u16>,
    pub update_counter5: Vec<u8>,
}
