use socket::{to, ServiceBuilder};

use crate::{
    adapters::handlers,
    config::middleware,
    protocol::{
        command::route_code as command_route_code, data::route_code as data_route_code,
        game_server::route_code as game_server_route_code, transcode::route_code,
    },
    proxy,
};

pub fn handlers_config(cfg: &mut ServiceBuilder) {
    cfg.default(proxy::forward_to_server)
        .before_extract(middleware::normalize_request)
        .service(to(handlers::from_client::ping::ping), route_code::Ping)
        .service(
            to(handlers::from_client::position::position),
            route_code::Position,
        )
        .service(
            to(handlers::from_client::motion_state::motion_state),
            route_code::MotionState,
        )
        .service(
            to(handlers::from_client::cast_buff_self_target_skill::cast_buff_self_target_skill),
            route_code::ProcessSkill2,
        )
        .service(
            to(handlers::from_client::party_skill::party_skill),
            route_code::PartySkill,
        )
        .service(
            to(handlers::from_client::cancel_skill::cancel_skill),
            route_code::CancelSkill,
        )
        .service(
            to(handlers::from_client::get_record_data::get_record_data),
            route_code::Getrecorddata,
        )
        .on_disconnect(handlers::from_client::connection::on_disconnect)
        .on_connection(handlers::from_client::connection::on_connect);
}

pub fn legacy_handlers_config(cfg: &mut ServiceBuilder) {
    cfg.default(proxy::forward_to_client)
        .before_extract(middleware::normalize_request)
        .service(to(handlers::from_server::ping::ping), route_code::Ping)
        .service(
            to(handlers::from_server::transplaydata::transplaydata),
            route_code::Transplaydata,
        )
        .service(
            to(handlers::from_server::playerinfo::playerinfo),
            route_code::Playerinfo,
        )
        .service(
            to(handlers::from_server::playerinfo2::playerinfo2),
            route_code::Playerinfo2,
        )
        .service(
            to(handlers::from_server::client_record_data::server_client_record_data),
            data_route_code::ClientRecordData,
        )
        .service(
            to(handlers::from_server::fail_record_data::fail_record_data),
            command_route_code::FailRecordData,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_meta),
            game_server_route_code::GameServerWarmupMeta,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_field),
            game_server_route_code::GameServerWarmupField,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_monster),
            game_server_route_code::GameServerWarmupMonster,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_npc),
            game_server_route_code::GameServerWarmupNpc,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_open_item),
            game_server_route_code::GameServerWarmupOpenItem,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area),
            game_server_route_code::GameServerWarmupStageArea,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area_npcs),
            game_server_route_code::GameServerWarmupStageAreaNpc,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area_start_points),
            game_server_route_code::GameServerWarmupStageAreaStartPoint,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area_monster_rules),
            game_server_route_code::GameServerWarmupStageAreaMonsterRule,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area_boss_rules),
            game_server_route_code::GameServerWarmupStageAreaBossRule,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_done),
            game_server_route_code::GameServerWarmupDone,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_snapshot_begin),
            game_server_route_code::WorldRuntimeSnapshotBegin,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_monster_sync),
            game_server_route_code::WorldRuntimeMonsterSync,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_monster_despawn),
            game_server_route_code::WorldRuntimeMonsterDespawn,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_npc_sync),
            game_server_route_code::WorldRuntimeNpcSync,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_npc_despawn),
            game_server_route_code::WorldRuntimeNpcDespawn,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_snapshot_end),
            game_server_route_code::WorldRuntimeSnapshotEnd,
        );
}

pub fn warmup_handlers_config(cfg: &mut ServiceBuilder) {
    cfg.default(handlers::from_server::game_server_warmup::ignore_unexpected_warmup_packet)
        .before_extract(middleware::normalize_request)
        .service(
            to(handlers::from_server::game_server_warmup::warmup_server_version),
            command_route_code::ServerVersion,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_meta),
            game_server_route_code::GameServerWarmupMeta,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_field),
            game_server_route_code::GameServerWarmupField,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_monster),
            game_server_route_code::GameServerWarmupMonster,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_npc),
            game_server_route_code::GameServerWarmupNpc,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_open_item),
            game_server_route_code::GameServerWarmupOpenItem,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area),
            game_server_route_code::GameServerWarmupStageArea,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area_npcs),
            game_server_route_code::GameServerWarmupStageAreaNpc,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area_start_points),
            game_server_route_code::GameServerWarmupStageAreaStartPoint,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area_monster_rules),
            game_server_route_code::GameServerWarmupStageAreaMonsterRule,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_stage_area_boss_rules),
            game_server_route_code::GameServerWarmupStageAreaBossRule,
        )
        .service(
            to(handlers::from_server::game_server_warmup::warmup_done),
            game_server_route_code::GameServerWarmupDone,
        )
        .on_disconnect(handlers::from_server::game_server_warmup::warmup_disconnect);
}

pub fn runtime_handlers_config(cfg: &mut ServiceBuilder) {
    cfg.default(handlers::from_server::game_server_runtime::ignore_unexpected_runtime_packet)
        .before_extract(middleware::normalize_request)
        .service(
            to(handlers::from_server::game_server_runtime::runtime_server_version),
            command_route_code::ServerVersion,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_snapshot_begin),
            game_server_route_code::WorldRuntimeSnapshotBegin,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_monster_sync),
            game_server_route_code::WorldRuntimeMonsterSync,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_monster_despawn),
            game_server_route_code::WorldRuntimeMonsterDespawn,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_npc_sync),
            game_server_route_code::WorldRuntimeNpcSync,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_npc_despawn),
            game_server_route_code::WorldRuntimeNpcDespawn,
        )
        .service(
            to(handlers::from_server::game_server_runtime::runtime_snapshot_end),
            game_server_route_code::WorldRuntimeSnapshotEnd,
        )
        .on_disconnect(handlers::from_server::game_server_runtime::runtime_disconnect);
}
